#!/usr/bin/env python3
"""Validate TESS against ideal dependence boundaries and a Gaussian-copula grid.

This is an idealized p-value experiment, not a rerun of the biomedical ML
pipeline. Candidate-wise p-values are exactly Uniform(0,1) under the global
null. The script checks that Tail-Equivalent Search Size (TESS):

* recovers 1 when all candidate p-values are identical;
* recovers nominal K when candidate p-values are independent; and
* takes intermediate, potentially alpha-dependent values under positive
  dependence generated by an equicorrelated Gaussian copula.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import matplotlib.pyplot as plt
import numpy as np
from scipy.special import ndtr

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from simulations.ess.ess_estimators import estimate_tail_ess


DEFAULT_ALPHAS = (0.20, 0.10, 0.05, 0.025, 0.01, 0.005)
DEFAULT_KS = (7, 20)
DEFAULT_RHOS = (0.25, 0.50, 0.75, 0.90, 0.99)


@dataclass(frozen=True)
class Scenario:
    name: str
    k: int
    rho: float | None = None


def parse_float_list(text: str) -> tuple[float, ...]:
    values = tuple(float(x.strip()) for x in text.split(",") if x.strip())
    if not values:
        raise ValueError("At least one value is required.")
    return values


def parse_int_list(text: str) -> tuple[int, ...]:
    values = tuple(int(x.strip()) for x in text.split(",") if x.strip())
    if not values:
        raise ValueError("At least one value is required.")
    return values


def exact_independent_rejection_probability(alpha: float, k: int) -> float:
    """P(min(P_1,...,P_K) < alpha) for independent Uniform(0,1) p-values."""
    return 1.0 - (1.0 - alpha) ** k


def exact_complete_dependence_rejection_probability(alpha: float) -> float:
    """P(P < alpha) when every candidate has the same Uniform(0,1) p-value."""
    return alpha


def _validate_inputs(alphas: Iterable[float], ks: Iterable[int], rhos: Iterable[float]) -> None:
    for alpha in alphas:
        if not 0.0 < alpha < 1.0:
            raise ValueError(f"alpha must be in (0,1); received {alpha}")
    for k in ks:
        if k < 1:
            raise ValueError(f"K must be positive; received {k}")
    for rho in rhos:
        if not 0.0 <= rho < 1.0:
            raise ValueError(f"rho must be in [0,1); received {rho}")


def simulate_rejection_counts(
    scenario: Scenario,
    alphas: tuple[float, ...],
    repetitions: int,
    chunk_size: int,
    rng: np.random.Generator,
) -> np.ndarray:
    """Return rejection counts for all alpha thresholds in one scenario."""
    counts = np.zeros(len(alphas), dtype=np.int64)
    thresholds = np.asarray(alphas, dtype=float)

    completed = 0
    while completed < repetitions:
        n = min(chunk_size, repetitions - completed)

        if scenario.name == "complete_dependence":
            min_p = rng.random(n)
        elif scenario.name == "independent":
            min_p = rng.random((n, scenario.k)).min(axis=1)
        elif scenario.name == "gaussian_copula":
            if scenario.rho is None:
                raise ValueError("Gaussian-copula scenario requires rho.")
            common = rng.standard_normal((n, 1))
            residual = rng.standard_normal((n, scenario.k))
            z = np.sqrt(scenario.rho) * common + np.sqrt(1.0 - scenario.rho) * residual
            # One-sided null p-values. Marginally Uniform(0,1).
            p_values = 1.0 - ndtr(z)
            min_p = p_values.min(axis=1)
        else:
            raise ValueError(f"Unknown scenario: {scenario.name}")

        counts += np.sum(min_p[:, None] < thresholds[None, :], axis=0)
        completed += n

    return counts


def build_scenarios(ks: tuple[int, ...], rhos: tuple[float, ...]) -> list[Scenario]:
    scenarios: list[Scenario] = []
    for k in ks:
        scenarios.append(Scenario("complete_dependence", k))
        scenarios.append(Scenario("independent", k))
        scenarios.extend(Scenario("gaussian_copula", k, rho) for rho in rhos)
    return scenarios


def summarize_scenario(
    scenario: Scenario,
    counts: np.ndarray,
    alphas: tuple[float, ...],
    repetitions: int,
) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for alpha, rejections in zip(alphas, counts, strict=True):
        estimate = estimate_tail_ess(int(rejections), repetitions, alpha)

        if scenario.name == "complete_dependence":
            exact_probability = exact_complete_dependence_rejection_probability(alpha)
            expected_tess = 1.0
        elif scenario.name == "independent":
            exact_probability = exact_independent_rejection_probability(alpha, scenario.k)
            expected_tess = float(scenario.k)
        else:
            exact_probability = np.nan
            expected_tess = np.nan

        rows.append(
            {
                "scenario": scenario.name,
                "nominal_candidate_count": scenario.k,
                "rho": scenario.rho if scenario.rho is not None else "",
                "local_alpha": alpha,
                "repetitions": repetitions,
                "rejections": int(rejections),
                "rejection_probability": estimate.rejection_probability,
                "rejection_probability_low_95": estimate.rejection_probability_low,
                "rejection_probability_high_95": estimate.rejection_probability_high,
                "tess": estimate.ess,
                "tess_low_95": estimate.ess_low,
                "tess_high_95": estimate.ess_high,
                "exact_rejection_probability": exact_probability,
                "expected_tess": expected_tess,
                "absolute_tess_error": (
                    abs(estimate.ess - expected_tess) if np.isfinite(expected_tess) else np.nan
                ),
            }
        )
    return rows


def write_csv(rows: list[dict[str, object]], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def _rows_for(rows: list[dict[str, object]], scenario: str, k: int, rho: float | None = None):
    selected = [
        row
        for row in rows
        if row["scenario"] == scenario
        and int(row["nominal_candidate_count"]) == k
        and (rho is None or np.isclose(float(row["rho"]), rho))
    ]
    return sorted(selected, key=lambda row: float(row["local_alpha"]), reverse=True)


def plot_boundary_recovery(rows: list[dict[str, object]], ks: tuple[int, ...], output_dir: Path) -> None:
    fig, ax = plt.subplots(figsize=(10, 6))
    for k in ks:
        for scenario, marker in (("complete_dependence", "o"), ("independent", "s")):
            subset = _rows_for(rows, scenario, k)
            alpha = np.array([float(row["local_alpha"]) for row in subset])
            tess = np.array([float(row["tess"]) for row in subset])
            low = np.array([float(row["tess_low_95"]) for row in subset])
            high = np.array([float(row["tess_high_95"]) for row in subset])
            label = f"{scenario.replace('_', ' ')}, K={k}"
            line = ax.plot(alpha, tess, marker=marker, label=label)[0]
            ax.fill_between(alpha, low, high, alpha=0.14, color=line.get_color())

    ax.set_xscale("log")
    ax.invert_xaxis()
    ax.set_xlabel("Local significance level (alpha)")
    ax.set_ylabel("Tail-equivalent search size (TESS)")
    ax.set_title("Boundary recovery: identical candidates versus independent candidates")
    ax.grid(True, alpha=0.25)
    ax.legend()
    fig.tight_layout()
    fig.savefig(output_dir / "tess_boundary_recovery.png", dpi=220)
    fig.savefig(output_dir / "tess_boundary_recovery.svg")
    plt.close(fig)


def plot_gaussian_dependence(
    rows: list[dict[str, object]],
    k: int,
    rhos: tuple[float, ...],
    output_dir: Path,
) -> None:
    fig, ax = plt.subplots(figsize=(10, 6))
    for rho in rhos:
        subset = _rows_for(rows, "gaussian_copula", k, rho)
        alpha = np.array([float(row["local_alpha"]) for row in subset])
        tess = np.array([float(row["tess"]) for row in subset])
        ax.plot(alpha, tess, marker="o", label=f"rho={rho:g}")

    ax.axhline(1.0, linewidth=1, linestyle="--", label="complete-dependence limit")
    ax.axhline(float(k), linewidth=1, linestyle=":", label=f"independence limit K={k}")
    ax.set_xscale("log")
    ax.invert_xaxis()
    ax.set_xlabel("Local significance level (alpha)")
    ax.set_ylabel("Tail-equivalent search size (TESS)")
    ax.set_title(f"TESS under equicorrelated Gaussian-copula p-values (K={k})")
    ax.grid(True, alpha=0.25)
    ax.legend(ncol=2)
    fig.tight_layout()
    fig.savefig(output_dir / f"tess_gaussian_dependence_K{k}.png", dpi=220)
    fig.savefig(output_dir / f"tess_gaussian_dependence_K{k}.svg")
    plt.close(fig)


def write_markdown_summary(
    rows: list[dict[str, object]],
    output_dir: Path,
    repetitions: int,
    seed: int,
) -> None:
    boundary_rows = [row for row in rows if row["scenario"] in {"complete_dependence", "independent"}]
    max_error = max(float(row["absolute_tess_error"]) for row in boundary_rows)

    independent_errors = [
        float(row["absolute_tess_error"]) for row in rows if row["scenario"] == "independent"
    ]
    dependent_errors = [
        float(row["absolute_tess_error"])
        for row in rows
        if row["scenario"] == "complete_dependence"
    ]

    lines = [
        "# TESS boundary-validation results",
        "",
        f"- Monte Carlo repetitions per scenario: {repetitions:,}",
        f"- Random seed: {seed}",
        f"- Maximum absolute boundary-recovery error: {max_error:.4f}",
        f"- Maximum error under independence: {max(independent_errors):.4f}",
        f"- Maximum error under complete dependence: {max(dependent_errors):.4f}",
        "",
        "## Interpretation",
        "",
        "The simulation uses valid Uniform(0,1) candidate-wise p-values under the global null.",
        "When all candidate p-values are identical, TESS should equal 1. When the K candidate",
        "p-values are independent, TESS should equal K. The Gaussian-copula scenarios provide",
        "intermediate positive-dependence cases and are descriptive rather than exact targets.",
        "",
        "This validation concerns the mathematical behavior of the TESS transformation. It is",
        "not a validation of the complete biomedical machine-learning pipeline or of a TESS-based",
        "multiplicity correction.",
    ]
    (output_dir / "TESS_BOUNDARY_VALIDATION_SUMMARY.md").write_text(
        "\n".join(lines) + "\n", encoding="utf-8"
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("simulations/ess/outputs/boundary_validation"),
    )
    parser.add_argument("--repetitions", type=int, default=1_000_000)
    parser.add_argument("--chunk-size", type=int, default=50_000)
    parser.add_argument("--seed", type=int, default=20260730)
    parser.add_argument("--alphas", default=",".join(str(x) for x in DEFAULT_ALPHAS))
    parser.add_argument("--ks", default=",".join(str(x) for x in DEFAULT_KS))
    parser.add_argument("--rhos", default=",".join(str(x) for x in DEFAULT_RHOS))
    args = parser.parse_args()

    alphas = parse_float_list(args.alphas)
    ks = parse_int_list(args.ks)
    rhos = parse_float_list(args.rhos)
    _validate_inputs(alphas, ks, rhos)
    if args.repetitions < 1_000:
        parser.error("--repetitions must be at least 1,000.")
    if args.chunk_size < 1:
        parser.error("--chunk-size must be positive.")

    output_dir = args.output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    master = np.random.SeedSequence(args.seed)
    scenarios = build_scenarios(ks, rhos)
    child_seeds = master.spawn(len(scenarios))

    rows: list[dict[str, object]] = []
    for index, (scenario, child_seed) in enumerate(zip(scenarios, child_seeds, strict=True), start=1):
        descriptor = scenario.name
        if scenario.rho is not None:
            descriptor += f" rho={scenario.rho:g}"
        print(f"[{index:02d}/{len(scenarios):02d}] {descriptor}, K={scenario.k}")
        rng = np.random.default_rng(child_seed)
        counts = simulate_rejection_counts(
            scenario=scenario,
            alphas=alphas,
            repetitions=args.repetitions,
            chunk_size=args.chunk_size,
            rng=rng,
        )
        rows.extend(summarize_scenario(scenario, counts, alphas, args.repetitions))

    write_csv(rows, output_dir / "tess_boundary_validation.csv")
    plot_boundary_recovery(rows, ks, output_dir)
    for k in ks:
        plot_gaussian_dependence(rows, k, rhos, output_dir)
    write_markdown_summary(rows, output_dir, args.repetitions, args.seed)

    config = {
        "repetitions": args.repetitions,
        "chunk_size": args.chunk_size,
        "seed": args.seed,
        "alphas": alphas,
        "ks": ks,
        "rhos": rhos,
        "interpretation": "Idealized candidate-wise null p-value validation; not a full pipeline rerun.",
    }
    (output_dir / "tess_boundary_validation_config.json").write_text(
        json.dumps(config, indent=2), encoding="utf-8"
    )

    boundary_rows = [row for row in rows if row["scenario"] in {"complete_dependence", "independent"}]
    max_error = max(float(row["absolute_tess_error"]) for row in boundary_rows)
    print("\nBoundary validation complete")
    print(f"Output directory: {output_dir}")
    print(f"Maximum absolute TESS boundary error: {max_error:.4f}")


if __name__ == "__main__":
    main()
